export const FETCH_USERS = 'FETCH_USERS';
export type FETCH_USERS = typeof FETCH_USERS;

export const FETCH_USERS_REJECT = 'FETCH_USERS_REJECT';
export type FETCH_USERS_REJECT = typeof FETCH_USERS_REJECT;

export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export type FETCH_USERS_FULFILLED = typeof FETCH_USERS_FULFILLED;

export type TActionTyps = FETCH_USERS | FETCH_USERS_REJECT | FETCH_USERS_FULFILLED;
